name: callanvalencia
favicon: null
layout_spectrum: 0.9565114809665829
typography_spectrum: 0.8481569460127503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.30903656291775405
  lightness: 0.15702462987974286
  saturation: 0.02832918521016836
  rhythmicContrast: 0.6584356350358576
purpose: []
